### ISSUE TITLE
目次ページ+自分の好きな食べ物紹介サイトの作成

### ISSUE THREAD

**Issue by s1f102101503** [s1f102101503/team-project#2]
目次ページの作成をお願いします。
詳しくは岩田がDMにワイヤーフレームを送りますのでそれを参考にしてください。
わからないことはお互いに質問しあって頑張りましょう！
これからよろしくお願いします！

**Comment by s1f10210106** [comment]
目次もうつくっちゃいました？自分サイトは完了しました。

**Comment by s1f10210106** [comment]
1.
